{
    'name': 'Hospital Management',
    'version': '13.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'Module for managing the Hospitals',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'Global Xs',
    'maintainer': 'Zain Developer',
    'website': 'www.globalxs.com',
    'depends': ['sale', 'mail', 'board', 'contacts', 'board', 'odoo_report_xlsx', 'web_notify', 'portal'],
    'demo': [],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence.xml',
        'data/mail_template.xml',
        'data/cron.xml',
        'data/data.xml',
        'wizard/create_appointment.xml',
        'views/patient.xml',
        'views/appointment.xml',
        'views/doctor.xml',
        'views/lab.xml',
        'views/templates.xml',
        'views/settings.xml',
        'views/sale_order.xml',
        'views/portal_template.xml',
        # 'views/dashboard.xml',
        'views/website_form.xml',
        'reports/patient_card.xml',
        'reports/appointment.xml',
        'reports/report.xml',
        'reports/sale_report_inherit.xml',
        'security/security.xml',
        # 'data/cron.xml',

        # 'view/appointment.xml',

    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,

}
